config/routes.rb
Rails.application.routes.draw do
    #authenticated :user do
    root 'home#index' #as: :authenticated_root
  #end

  #root "home#landing"

  #root "home#index"
  resources :home do
    collection do
      get 'landing'
      post 'landing'
    end
  end
  resources :works
  resources :contacts
  resources :educations
  resources :social_info
  resources :phones
  resources :emails
  resources :labels
  devise_for :users, path: "MyPata",:controllers => { :omniauth_callbacks => "callbacks" },  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'sign_up'}
  get "/invites" => "invites#index"
  get "/:id" => "profile#show"
  get "/profile/menu", to: "profile#menu"
  get "/:nick/add", to:"profile#add_contact", as: 'add_contact'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/social_info.rb
class SocialInfo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8
  class User < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :phones
  has_many :emails
  has_many :works
  has_many :educations
  has_one :social_info
  has_one :hashtag
  has_many :interests
  has_many :labels
  has_many :contacts

  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  #before_save :downcase_fields
  


def self.from_omniauth(auth)
  if self.where(email: auth.info.email).exists?
    return_user = self.where(email: auth.info.email).first
    return_user.provider = auth.provider
    return_user.uid = auth.uid
  else
    return_user = self.create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.avatar = auth.info.image
       
       user.nick = auth.info.name
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
    end
  end

  return_user
end
   #def downcase_fields
   #  self.nick.downcase!
   #end
 #mount_uploader :avatar, AvatarUploader
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
	before_action :set_label, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!

	def index
		@labels = current_user.labels
	end


	def show
  	end


	def new 
		@label = current_user.labels.build
	end

	def create
		@label = current_user.labels.build(label_params)

		if @label.save
			redirect_to @label
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @label.update(label_params)    
                redirect_to @label    
            else   
                render 'edit'    
            end 
	end

	def destroy
		@label.destroy
		
		render 'index'
	end

	private

	def set_label
		@label = current_user.labels.find(params[:id])
	end

	def label_params
		params.require(:label).permit(:name, :field)
	end

end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/labels/_footer.html.erb
 <footer>
        <div class="container">
            <p>&copy; 2016 Start Bootstrap. All Rights Reserved.</p>
            <ul class="list-inline">
                <li>
                    <a href="#">Privacy</a>
                </li>
                <li>
                    <a href="#">Terms</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
            </ul>
        </div>
    </footer>

app/views/labels/_form.html.erb
<%= form_for @label, :html => { :class => "form-horizontal label" } do |f| %>

  <% if @label.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group", style="color: black;">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group", style="color: black;">
    <%= f.label :field, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :field, :class => 'form-control' %>
    </div>
    <%=f.error_span(:field) %>
  </div>
  <div class="form-group", style="color: black;">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                labels_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/labels/_form2.html.erb
<%= form_for @label, :html => { :class => "form-horizontal label" } do |f| %>

  <% if @label.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @label.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
 
<div class="container">
    <div class="row">

        <div class="row">
            <div class="col-sm-8">

                <h4 class="page-header">new label</h4>
                <form role="form">

                    <div class="form-group float-label-control">
                        <%= f.label :name, :class => 'form-group float-label-control' %>
                        <%= f.text_field :name, :class => 'form-control',placeholder: 'name'%>
                    <%=f.error_span(:name) %>    
                    </div>

                    <div class="form-group float-label-control">
                       <%= f.label :field, :class => 'form-group float-label-control' %>
                        <%= f.text_field :field, :class => 'form-control',placeholder: 'field'%>
                    <%=f.error_span(:field) %>    
                    </div>
                    <div class="form-group float-label-control">
                        <%= f.label :field, :class => 'form-group float-label-control' %>
                        <%= f.text_field :field, :class => 'form-control',placeholder: 'field'%>
                    <%=f.error_span(:field) %>   
                    </div>
                </form>


               


                
            </div>
        </div>
    </div>
</div>
 <% end %>
 <%end%>
<style type="text/css">
    .float-label-control { position: relative; margin-bottom: 1.5em; }
    .float-label-control ::-webkit-input-placeholder { color: transparent; }
    .float-label-control :-moz-placeholder { color: transparent; }
    .float-label-control ::-moz-placeholder { color: transparent; }
    .float-label-control :-ms-input-placeholder { color: transparent; }
    .float-label-control input:-webkit-autofill,
    .float-label-control textarea:-webkit-autofill { background-color: transparent !important; -webkit-box-shadow: 0 0 0 1000px white inset !important; -moz-box-shadow: 0 0 0 1000px white inset !important; box-shadow: 0 0 0 1000px white inset !important; }
    .float-label-control input, .float-label-control textarea, .float-label-control label { font-size: 1.3em; box-shadow: none; -webkit-box-shadow: none; }
        .float-label-control input:focus,
        .float-label-control textarea:focus { box-shadow: none; -webkit-box-shadow: none; border-bottom-width: 2px; padding-bottom: 0; }
        .float-label-control textarea:focus { padding-bottom: 4px; }
    .float-label-control input, .float-label-control textarea { display: block; width: 100%; padding: 0.1em 0em 1px 0em; border: none; border-radius: 0px; border-bottom: 1px solid #aaa; outline: none; margin: 0px; background: none; }
    .float-label-control textarea { padding: 0.1em 0em 5px 0em; }
    .float-label-control label { position: absolute; font-weight: normal; top: -1.0em; left: 0.08em; color: #aaaaaa; z-index: -1; font-size: 0.85em; -moz-animation: float-labels 300ms none ease-out; -webkit-animation: float-labels 300ms none ease-out; -o-animation: float-labels 300ms none ease-out; -ms-animation: float-labels 300ms none ease-out; -khtml-animation: float-labels 300ms none ease-out; animation: float-labels 300ms none ease-out; /* There is a bug sometimes pausing the animation. This avoids that.*/ animation-play-state: running !important; -webkit-animation-play-state: running !important; }
    .float-label-control input.empty + label,
    .float-label-control textarea.empty + label { top: 0.1em; font-size: 1.5em; animation: none; -webkit-animation: none; }
    .float-label-control input:not(.empty) + label,
    .float-label-control textarea:not(.empty) + label { z-index: 1; }
    .float-label-control input:not(.empty):focus + label,
    .float-label-control textarea:not(.empty):focus + label { color: #aaaaaa; }
    .float-label-control.label-bottom label { -moz-animation: float-labels-bottom 300ms none ease-out; -webkit-animation: float-labels-bottom 300ms none ease-out; -o-animation: float-labels-bottom 300ms none ease-out; -ms-animation: float-labels-bottom 300ms none ease-out; -khtml-animation: float-labels-bottom 300ms none ease-out; animation: float-labels-bottom 300ms none ease-out; }
    .float-label-control.label-bottom input:not(.empty) + label,
    .float-label-control.label-bottom textarea:not(.empty) + label { top: 3em; }


@keyframes float-labels {
    0% { opacity: 1; color: #aaa; top: 0.1em; font-size: 1.5em; }
    20% { font-size: 1.5em; opacity: 0; }
    30% { top: 0.1em; }
    50% { opacity: 0; font-size: 0.85em; }
    100% { top: -1em; opacity: 1; }
}

@-webkit-keyframes float-labels {
    0% { opacity: 1; color: #aaa; top: 0.1em; font-size: 1.5em; }
    20% { font-size: 1.5em; opacity: 0; }
    30% { top: 0.1em; }
    50% { opacity: 0; font-size: 0.85em; }
    100% { top: -1em; opacity: 1; }
}

@keyframes float-labels-bottom {
    0% { opacity: 1; color: #aaa; top: 0.1em; font-size: 1.5em; }
    20% { font-size: 1.5em; opacity: 0; }
    30% { top: 0.1em; }
    50% { opacity: 0; font-size: 0.85em; }
    100% { top: 3em; opacity: 1; }
}

@-webkit-keyframes float-labels-bottom {
    0% { opacity: 1; color: #aaa; top: 0.1em; font-size: 1.5em; }
    20% { font-size: 1.5em; opacity: 0; }
    30% { top: 0.1em; }
    50% { opacity: 0; font-size: 0.85em; }
    100% { top: 3em; opacity: 1; }
}
</style>
<script>
/* Float Label Pattern Plugin for Bootstrap 3.1.0 by Travis Wilson
**************************************************/

(function ($) {
    $.fn.floatLabels = function (options) {

        // Settings
        var self = this;
        var settings = $.extend({}, options);


        // Event Handlers
        function registerEventHandlers() {
            self.on('input keyup change', 'input, textarea', function () {
                actions.swapLabels(this);
            });
        }


        // Actions
        var actions = {
            initialize: function() {
                self.each(function () {
                    var $this = $(this);
                    var $label = $this.children('label');
                    var $field = $this.find('input,textarea').first();

                    if ($this.children().first().is('label')) {
                        $this.children().first().remove();
                        $this.append($label);
                    }

                    var placeholderText = ($field.attr('placeholder') && $field.attr('placeholder') != $label.text()) ? $field.attr('placeholder') : $label.text();

                    $label.data('placeholder-text', placeholderText);
                    $label.data('original-text', $label.text());

                    if ($field.val() == '') {
                        $field.addClass('empty')
                    }
                });
            },
            swapLabels: function (field) {
                var $field = $(field);
                var $label = $(field).siblings('label').first();
                var isEmpty = Boolean($field.val());

                if (isEmpty) {
                    $field.removeClass('empty');
                    $label.text($label.data('original-text'));
                }
                else {
                    $field.addClass('empty');
                    $label.text($label.data('placeholder-text'));
                }
            }
        }


        // Initialization
        function init() {
            registerEventHandlers();

            actions.initialize();
            self.each(function () {
                actions.swapLabels($(this).find('input,textarea').first());
            });
        }
        init();


        return this;
    };

    $(function () {
        $('.float-label-control').floatLabels();
    });
})(jQuery);
</script>

app/views/labels/edit.html.erb
<%- model_class = Label -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/labels/index.html.erb
<%- model_class = Label -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:field) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= link_to label.id, label_path(label) %></td>
        <td><%= label.name %></td>
        <td><%= label.field %></td>
        <td><%= label.user_id %></td>
        <td><%=l label.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_label_path(label), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      label_path(label),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_label_path,
            :class => 'btn btn-primary' %>

app/views/labels/new.html.erb
<%- model_class = Label -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/labels/show.html.erb
<%- model_class = Label -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @label.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:field) %>:</strong></dt>
  <dd><%= @label.field %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @label.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              labels_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_label_path(@label), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              label_path(@label),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>