config/routes.rb
Rails.application.routes.draw do
    #authenticated :user do
    root 'home#index' #as: :authenticated_root
  #end

  #root "home#landing"

  #root "home#index"
  resources :home do
    collection do
      get 'landing'
      post 'landing'
    end
  end
  resources :works
  resources :contacts
  resources :educations
  resources :social_info
  resources :phones
  resources :emails
  resources :labels
  devise_for :users, path: "MyPata",:controllers => { :omniauth_callbacks => "callbacks" },  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'sign_up'}
  get "/invites" => "invites#index"
  get "/:id" => "profile#show"
  get "/profile/menu", to: "profile#menu"
  get "/:nick/add", to:"profile#add_contact", as: 'add_contact'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
  belongs_to :user
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/social_info.rb
class SocialInfo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8
  class User < ApplicationRecord
    mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :phones
  has_many :emails
  has_many :works
  has_many :educations
  has_one :social_info
  has_one :hashtag
  has_many :interests
  has_many :labels
  has_many :contacts

  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]
  #before_save :downcase_fields
  


def self.from_omniauth(auth)
  if self.where(email: auth.info.email).exists?
    return_user = self.where(email: auth.info.email).first
    return_user.provider = auth.provider
    return_user.uid = auth.uid
  else
    return_user = self.create do |user|
       user.provider = auth.provider
       user.uid = auth.uid
       user.avatar = auth.info.image
       
       user.nick = auth.info.name
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
    end
  end

  return_user
end
   #def downcase_fields
   #  self.nick.downcase!
   #end
 #mount_uploader :avatar, AvatarUploader
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
before_action :set_education, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!

	def index
		@educations = current_user.educations
	end


	def show
  	end


	def new 
		@education = current_user.educations.build
	end

	def create
		@education = current_user.educations.build(education_params)

		if @education.save
			redirect_to @education
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @education.update(education_params)    
                redirect_to @education    
            else   
                render 'edit'    
            end 
	end

	def destroy
		@education.destroy
		
		render 'index'
	end

	private

	def set_education
		@education = current_user.educations.find(params[:id])
	end

	def education_params
		params.require(:education).permit(:institute, :details, :active, :start_date, :end_date)
	end

end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/educations/_form.html.erb
<%= form_for @education, :html => { :class => "form-horizontal education" } do |f| %>

  <% if @education.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @education.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :institute, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :institute, :class => 'form-control' %>
    </div>
    <%=f.error_span(:institute) %>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-6">
      <%= f.text_field :details, :class => 'form-control' %>
    </div>
    <%=f.error_span(:details) %>
  </div>
  
  <div class="form-group">
    <%= f.label :start_date, :class => 'control-label col-lg-2' %>
    <div class="col-sm-2">
      <%= f.date_field :start_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:start_date) %>
  </div>
  <div class="form-group">
    <%= f.label :end_date, :class => 'control-label col-lg-2' %>
    <div class="col-sm-2">
      <%= f.date_field :end_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_date) %>
  </div>
  <div class="form-group">
    <%= f.label :active, :class => 'control-label col-lg-2' %>
    <div class="col-sm-1">
      <%= f.check_box :active, :class => 'form-control' %>
    </div>
    <%=f.error_span(:active) %>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Save", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                educations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/educations/edit.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/index.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:institute) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= link_to education.id, education_path(education) %></td>
        <td><%= education.institute %></td>
        <td><%= education.details %></td>
        <td><%= education.active %></td>
        <td><%= education.start_date %></td>
        <td><%= education.end_date %></td>
        <td><%= education.user_id %></td>
        <td><%=l education.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_education_path(education), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      education_path(education),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_education_path,
            :class => 'btn btn-primary' %>

app/views/educations/new.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/educations/show.html.erb
<%- model_class = Education -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:institute) %>:</strong></dt>
  <dd><%= @education.institute %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @education.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @education.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @education.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @education.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @education.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              educations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_education_path(@education), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              education_path(@education),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>